[r1]
name = "B0XX r1"
id = "r1"
partno = "atmega32u4"
progid = "avr109"
baudrate = 57600
memtype = "flash"
op = "w"
active = true

[[r1.firmwares]]
version = "2.11"
date = 2019-10-08T05:17:00Z
active = true
legal = true
filename = "B0XX_r1_2.11.hex"
filefmt = "i"

[[r1.firmwares]]
version = "2.13"
date = 2019-12-26T11:00:00Z
active = true
legal = true
filename = "B0XX_r1_2.13.hex"
filefmt = "i"

[[r1.firmwares]]
version = "2.14"
date = 2020-01-01T06:47:00Z
active = true
legal = true
filename = "B0XX_r1_2.14.hex"
filefmt = "i"

[r2]
name = "B0XX r2"
id = "r2"
partno = ""
progid = ""
baudrate = 0
memtype = "flash"
op = "w"
active = false
firmwares = []
